### PR TITLE
TTbar example

### PR DESCRIPTION
**Pull request by swertz**
For the moment it's just a copy of the internal MoMEMta ttbar example, but 
- loading a matrix element generated by the exporter and built separately
- linking against MoMEMta as external dependency, using a FindMoMEMta.cmake module

Before going on, I'd welcome any input on how to structure this tutorials repository...

### CODE REVIEW

**Comment by swertz** [comment]
I'm surprised the ".swp" files got into the commit... They are listed as untracked when I do a git status (and I cannot git rm them) :-|

**Comment by swertz** [comment]
Update: the ttbar example with a small sample and an example of an event loop is done.

**Comment by blinkseb** [comment]
Looks good thanks! How big is the ROOT file?

**Comment by swertz** [comment]
15k!

**Comment by blinkseb** [comment]
Good :+1:

**Pull request merged**
